"""
Intake to Brand Bible drafter (manual CLI, Stage 2 onboarding).

  /opt/venv/bin/python -m agent draft-bible --client <key> --intake <path>

Parses a completed BRAND_VOICE_INTAKE.md (numbered `## N.` section headings are the
anchors) and generates a DRAFT brand bible in the lasso_voice.md structure, plus a
draft social_proof.md from section 6 (only entries with Permission: yes become
entries; everything else is listed in a Skipped block with its reason).

Output goes to brand_voice/drafts/<client>/ and is NEVER auto-activated: activation
is a human reviewing and copying the files by hand. Missing or empty sections render
as explicit TODO blocks, never guessed content. Manual-only BY DESIGN (like
capture-baseline): no flag, never scheduled, nothing in the agent imports it.
"""

import os
import re

DRAFTS_DIR = os.path.join("brand_voice", "drafts")

TODO = "> TODO: this section was missing or empty in the intake. Fill it by hand before activation."

# The fixed copy-mechanics guardrails every client bible carries (house rules, not
# client facts): they mirror lasso_voice.md's non-negotiables.
BASELINE_GUARDRAILS = """- Every post waits for human approval. No exceptions.
- No invented offers, prices, stats, guarantees, or client names. If the fact is not
  in this doc or the creative note, it does not ship.
- Client wins are used only with recorded permission (see social_proof.md).
- Copy mechanics: no em dashes, no en dashes, avoid hyphens in published copy.
  Rewrite the sentence instead. Use the word "to" for ranges."""


def parse_intake(text):
    """{section_number: body} from `## N.` headings. Bodies keep their sub-lines."""
    sections = {}
    current, buf = None, []
    for line in (text or "").splitlines():
        m = re.match(r"^##\s*(\d+)[.)]?\s", line)
        if m:
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current, buf = int(m.group(1)), []
        elif current is not None:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()
    return sections


def _sec(sections, n):
    body = (sections.get(n) or "").strip()
    return body if body else TODO


def parse_proof_entries(section6):
    """(kept, skipped) from section 6. kept = Permission yes; skipped = (entry_text,
    reason). A missing Verified date stays a TODO line inside the entry; the runtime
    social proof gate still refuses to render until a real date is filled in."""
    kept, skipped = [], []
    blocks = re.split(r"\n\s*\n", section6 or "")
    for block in blocks:
        fields = {}
        for line in block.splitlines():
            m = re.match(r"^\s*(Quote|Stat|Support|Attribution|Permission|Verified)\s*:\s*(.*?)\s*$",
                         line, re.IGNORECASE)
            if m:
                fields[m.group(1).lower()] = m.group(2).strip()
        main = fields.get("quote") or fields.get("stat")
        if not main:
            continue
        if fields.get("permission", "").lower() != "yes":
            skipped.append((main, "permission is not yes"))
            continue
        lines = ["## Entry"]
        lines.append(f"Quote: {fields['quote']}" if fields.get("quote") else f"Stat: {fields['stat']}")
        if fields.get("support"):
            lines.append(f"Support: {fields['support']}")
        lines.append(f"Attribution: {fields.get('attribution', 'TODO')}")
        lines.append("Permission: yes")
        lines.append(f"Verified: {fields.get('verified') or 'TODO fill a real YYYY-MM-DD date'}")
        kept.append("\n".join(lines))
    return kept, skipped


def draft_bible(client, intake_text):
    """(bible_md, social_proof_md) drafted STRICTLY from the intake's own words."""
    s = parse_intake(intake_text)
    name = client.replace("_", " ").title()

    bible = f"""# {name} Brand Bible — Echo Social Agent (DRAFT, generated from intake)

> DRAFT ONLY. Generated by `python -m agent draft-bible`; NEVER auto-activated.
> A human reviews this, fills every TODO, and copies it into place by hand.

## 1. Who {name} is
{_sec(s, 1)}

## 2. Who we talk TO (the avatar)
{_sec(s, 2)}

## 3. Voice and tone
{_sec(s, 3)}

## 4. Hard guardrails (never violate)
{BASELINE_GUARDRAILS}

Client-specific guardrails from the intake:
{_sec(s, 4)}

## 5. Content pillars
{_sec(s, 5)}

## 6. Platform rules

### CTA rotation (cycle in order, one per post)
{_sec(s, 7)}

### Hashtag strategy (3 to 5 per post)
{_sec(s, 7) if (s.get(7) or '').strip() else TODO}
"""

    kept, skipped = parse_proof_entries(s.get(6, ""))
    proof_lines = [f"# {name} social proof (DRAFT from intake section 6; review before activation)",
                   ""]
    proof_lines.extend(kept if kept else
                       ["> TODO: no permissioned entries in the intake. Collect proof with"
                        " permission and a verified date before this file activates."])
    if skipped:
        proof_lines.append("\n## Skipped (never render these; fix the reason first)")
        for main, reason in skipped:
            proof_lines.append(f"- \"{main[:80]}\" skipped: {reason}")
    return bible, "\n".join(proof_lines) + "\n"


def run(client, intake_path):
    """Read the intake, write the two drafts under brand_voice/drafts/<client>/."""
    with open(intake_path, encoding="utf-8") as fh:
        intake_text = fh.read()
    bible, proof = draft_bible(client, intake_text)
    out_dir = os.path.join(DRAFTS_DIR, client)
    os.makedirs(out_dir, exist_ok=True)
    bible_path = os.path.join(out_dir, "lasso_voice.md")
    proof_path = os.path.join(out_dir, "social_proof.md")
    with open(bible_path, "w", encoding="utf-8") as fh:
        fh.write(bible)
    with open(proof_path, "w", encoding="utf-8") as fh:
        fh.write(proof)
    return bible_path, proof_path
