"""
gbp_mirror.py — every feed post Echo builds for a gym ALSO lands on that gym's Google
Business Profile.

Blake, 2026-09-02: "yes use GBP planner tha anytime you post to ig, fb or whatever goes
to google as well".

WHY THIS EXISTS
Echo already cross-posts at BUILD time: client_month_run._to_rows duplicates every
Instagram FEED row with account='facebook', and that mirrored row then flows through the
one approval + publish path that already works. Google Business had no equivalent. Its
content came only from the separate monthly planner (gbp_planner, fanned out by
jobs/gbp_month_sweep), which draws photos from its own `_gbp` rotation namespace and its
facts from client_sources — a DIFFERENT month from the one the gym actually sees on
Instagram, and it reached 6 of the 10 Google-connected gyms. So a gym could approve a
month of real posts and its Google listing would show something else, or nothing.

This is the Facebook mirror's mechanism pointed at Google, at the same moment in the
build, writing through the same door (SupabaseCalendarStore.insert_rows). It is NOT a
dict copy, because a Google post is not an Instagram post:

  1. CROP. Google wants 1200x900 (4:3); an IG feed card is square or portrait. Each
     mirrored row is cropped AND HOSTED at build time through gbp_planner's own
     _cropped_image_url, so the owner approves the exact pixels that publish (§5.3, no
     post-approval transform ever). That path needs R2 hosting, so mirroring only
     produces rows where hosting is configured (the deployed worker).
  2. CAPTION. An IG caption is the wrong copy for a Google listing (hashtags are
     forbidden, the first 80 characters carry the whole message in Search, the city is a
     ranking signal, 1500-char hard cap). The mirrored caption is generated by
     gbp_planner.generate_gbp_caption grounded ONLY on the gym's already-approved feed
     caption (its meta block and hashtags stripped) plus the gym's voice doc — the same
     figure gate (_output_claims_cleared) and the same A+ gate (gbp.caption_issues) as
     the planner. If it cannot be made A+, the row is SKIPPED. A+ or nothing: a degraded
     post on a client's Google listing is worse than no post, and nothing is fabricated.
  3. STORIES NEVER MIRROR. Stories are Instagram-only in Echo, so only FEED rows mirror,
     exactly like the Facebook leg.
  4. INFOGRAPHICS NEVER MIRROR. A house-rendered card already carries its own on-image
     copy laid out for a square feed; a 4:3 cover-crop would cut its own words off.
  5. CONNECTED GYMS ONLY. A gym whose GBP connection is 'needs_reconnect' (or absent)
     gets NO googlebusiness rows — the queue must never fill with posts that cannot
     publish (the same rule gbp_dogfood G4 enforces, tightened: even 'none' is skipped
     here, because a mirror runs every build and would otherwise stockpile rows for a gym
     that never connects).
  6. THE APPROVAL GATE IS UNTOUCHED. Rows land 'pending' and wait for the gym's own tap.
     Never 'coach_review' (Blake ruled it out for GBP), never 'approved'.

DOUBLE-MONTH INTERACTION (verified, not assumed): the month sweep's per-gym idempotency
is gbp_dogfood.plan_gbp_dogfood -> store.future_gbp_rows(gym, today), which counts ACTIVE
googlebusiness rows on/after today whatever their source. Mirrored rows are exactly that,
so once a gym's build has mirrored, the sweep reports 'already_planned' for it and writes
nothing. In the other order the sweep's own pending rows are wipeable, so the build's
delete-then-insert replaces them with the mirrored month. Neither order produces two GBP
months for one gym. See tests/test_gbp_mirror.py.

Behind AGENT_GBP_MIRROR, default OFF. Flag off => not one extra read, not one LLM call,
and the batch of calendar rows is byte-for-byte what it is today.
"""

from __future__ import annotations

import os
import re

from . import config, gbp

# a video creative has no still to hand Google; its POSTER frame is used instead (the
# same frame the portal already shows for that post), and only when it is local.
_VIDEO_EXTS = (".mp4", ".mov", ".m4v", ".webm")

# hashtag-only lines and a trailing inline hashtag run. Used ONLY to sanitize the
# grounding text handed to the caption generator, never to produce client copy.
_HASHTAG_LINE_RE = re.compile(r"^\s*(?:#\S+\s*)+$")
_TRAILING_TAGS_RE = re.compile(r"(?:\s+#\S+)+\s*$")

# the accounts a FEED row may carry and still be the Instagram original (the Facebook
# mirror is a duplicate of it and must never mirror again, or Google gets each post
# twice). Same test the Facebook leg itself uses.
_IG_ACCOUNTS = ("instagram", "ig", "")


# ---- pure helpers ---------------------------------------------------------------------

def is_story(draft) -> bool:
    """True for a story draft (is_story wins, draft_type is the belt-and-braces
    fallback) — the same reading real_calendar_mirror._draft_format does."""
    if getattr(draft, "is_story", False):
        return True
    return str(getattr(draft, "draft_type", "") or "").lower() == "story"


def source_fact(caption) -> str:
    """The gym's approved feed caption reduced to its FACTS, for use as the grounding
    text of the Google caption: the bracketed edit-rationale meta block removed (that is
    internal reasoning, never client copy), hashtag-only lines dropped and a trailing
    inline hashtag run trimmed (GBP forbids hashtags, so feeding them in only invites a
    caption that fails the gate).

    Nothing is added and no wording is rewritten — this only REMOVES. Returns "" when
    nothing but scaffolding/hashtags was there, and the caller then skips the row."""
    cap = str(caption or "")
    try:
        from .post_quality import split_meta_suffix
        body, meta = split_meta_suffix(cap)
        if meta and body.strip():
            cap = body
        elif meta:
            return ""          # the whole caption was scaffolding: nothing real to carry
    except Exception:  # noqa: BLE001 - the strip is an improvement, never a gate
        pass
    lines = [ln for ln in cap.splitlines() if not _HASHTAG_LINE_RE.match(ln)]
    cap = "\n".join(lines).strip()
    cap = _TRAILING_TAGS_RE.sub("", cap).strip()
    return cap


def is_infographic(draft) -> bool:
    """True when the creative is a HOUSE-RENDERED infographic card. Those already carry
    their own on-image copy, laid out for a square feed; a 4:3 cover-crop for Google
    would cut their own words off, so they never mirror."""
    try:
        from .client_month_run import _is_infographic_creative
        return bool(_is_infographic_creative(draft))
    except Exception:  # noqa: BLE001 - unresolvable -> treat as a normal photo
        return False


def eligible_drafts(drafts):
    """The drafts that MAY produce a googlebusiness row. PURE: no I/O, no flag read.

    A candidate is a FEED draft (never a story) on the Instagram leg, with a real
    post_date, a real caption whose facts survive source_fact, and a creative that is not
    a house-rendered infographic. Everything else is dropped here so the impure lane
    below never pays for a crop or an LLM call it cannot use."""
    out = []
    for draft in drafts or []:
        if draft is None or is_story(draft):
            continue
        plat = str(getattr(draft, "platform", "") or "").lower()
        if plat not in _IG_ACCOUNTS:
            continue
        day_key = (getattr(draft, "day_key", "") or "")[:10] or \
            (getattr(draft, "scheduled_for", "") or "")[:10]
        if not day_key:
            continue
        if not source_fact(getattr(draft, "caption", "")):
            continue
        if is_infographic(draft):
            continue
        out.append(draft)
    return out


def post_date_of(draft) -> str:
    """The mirrored row's post_date (YYYY-MM-DD), read exactly as the shared row builder
    reads it: day_key first, then the date part of scheduled_for."""
    day_key = (getattr(draft, "day_key", "") or "").strip()
    if day_key:
        return day_key[:10]
    sched = (getattr(draft, "scheduled_for", "") or "").strip()
    return sched[:10] if sched else ""


# ---- context resolution (real material only) ------------------------------------------

def resolve_context(base_key, *, store=None, address_fn=None, logger=None):
    """Everything a mirrored row needs, resolved from the gym's OWN real records, or
    None with a logged reason. Never guesses and never fabricates.

      * connection: must be 'connected' (see rule 5 in the module docstring).
      * city: from the gym's own verified Google listing address (the same read the month
        sweep uses). No readable city -> no mirror, never a guessed location.
      * voice: the gym's brand bible. Missing -> BLOCK, exactly like the planner.
      * cta_url: the gym's real GHL funnel link from onboarding_intake (gbp_planner's
        documented CTA source). Absent -> "" and the CTA button is simply omitted, which
        is a valid GBP post (gbp.build_platform_data).
    """
    log = logger or (lambda m: print(f"[gbp-mirror] {m}"))
    if store is None:
        from .gbp_store import GbpStore
        store = GbpStore()
        if not store.available():
            log(f"{base_key}: portal store unavailable -> no Google rows")
            return None
    # A GBP store (not the plain calendar store) is required: the connection posture and
    # the CTA link are only readable through it. Fail LOUDLY rather than silently
    # returning "not connected" for every gym, which is the exact shape of a no-op that
    # reports success (the silent-failure class this repo has been burned by).
    for method in ("connections_for", "onboarding_intake"):
        if not hasattr(store, method):
            log(f"{base_key}: the store passed to the Google mirror cannot read "
                f"{method} (it is not a GbpStore) -> no Google rows; this is a wiring "
                "bug, not a gym state")
            return None

    from . import gbp_dogfood
    status = gbp_dogfood._connection_status(base_key, store)
    if status != "connected":
        log(f"{base_key}: GBP connection is '{status}', not 'connected' -> no Google "
            "rows (never queue posts that cannot publish)")
        return None

    if address_fn is None:
        from .jobs.gbp_month_sweep import _gbp_address_for as address_fn
    from .jobs.gbp_month_sweep import city_from_address
    address = ""
    try:
        address = address_fn(base_key)
    except Exception as exc:  # noqa: BLE001 - a flaky read is a SKIP, never a guess
        log(f"{base_key}: listing address read failed ({type(exc).__name__})")
    city = city_from_address(address)
    if not city:
        log(f"{base_key}: no readable city on the Google listing ({address!r}) -> no "
            "Google rows (never planned against a guess)")
        return None

    voice = gbp_dogfood._resolve_voice(base_key)
    if voice is None:
        log(f"{base_key}: voice doc missing -> BLOCK, no Google rows (no fabrication)")
        return None

    cta_url = ""
    try:
        rec = store.onboarding_intake(base_key) or {}
        cta_url = str(rec.get("ghl_link") or "").strip()
    except Exception:  # noqa: BLE001 - no link just means no button
        cta_url = ""

    return {"city": city, "voice": voice, "cta_url": cta_url,
            "account_gen_key": f"{base_key}_ig"}


# ---- image + caption (the two things that are not a dict copy) ------------------------

def _local_still(draft, library_path, log):
    """(path, cleanup_path): a LOCAL still image to crop for Google, or (None, None).

    A photo creative is used directly. A VIDEO's poster frame is used instead (the frame
    the portal already shows for that post) and only when the video itself is local — a
    remote video is not downloaded at build time. A remote photo (the Drive lane) IS
    localized from its hosted url, the same way the story burn does it, and the temp file
    is reported back for cleanup."""
    path = (getattr(draft, "creative_path", "") or "").strip()
    if path and path.lower().endswith(_VIDEO_EXTS):
        if not os.path.isfile(path) or not library_path:
            # no local video, or no library to cache the frame in -> no still for Google
            return None, None
        try:
            from . import action_reel
            poster = action_reel.get_or_make_poster(path, library_path, logger=log)
        except Exception as exc:  # noqa: BLE001
            log(f"poster for {os.path.basename(path)} failed ({type(exc).__name__})")
            return None, None
        return (poster, None) if poster else (None, None)
    if path and os.path.isfile(path):
        return path, None
    url = (getattr(draft, "creative_public_url", "") or "").strip()
    if not url or url.split("?")[0].lower().endswith(_VIDEO_EXTS):
        return None, None
    try:
        import tempfile
        from . import media_host
        data = media_host.download_bytes(url)
        if not data:
            return None, None
        ext = os.path.splitext(path)[1] or \
            os.path.splitext(url.split("?")[0])[1] or ".jpg"
        fd, tmp = tempfile.mkstemp(suffix=ext)
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
        return tmp, tmp
    except Exception as exc:  # noqa: BLE001 - never block a build on a fetch
        log(f"could not localize hosted media for the Google crop "
            f"({type(exc).__name__})")
        return None, None


def cropped_url(draft, ctx, library_path, log):
    """The mirrored row's image_url: the draft's own creative cover-cropped to 1200x900
    and HOSTED, through gbp_planner's own crop-and-host path. None when there is no local
    still, the crop fails, or hosting is off."""
    import types
    path, cleanup = _local_still(draft, library_path, log)
    if not path:
        return None
    try:
        from . import gbp_planner
        return gbp_planner._cropped_image_url(
            ctx["account_gen_key"], types.SimpleNamespace(path=path),
            post_date_of(draft))
    finally:
        if cleanup:
            try:
                os.unlink(cleanup)
            except OSError:
                pass


def gbp_caption(draft, ctx, caption_fn=None):
    """The mirrored row's caption: a Google-native caption generated from the gym's
    already-approved feed caption (its facts only) plus the gym's voice doc, which must
    clear the SAME figure gate and A+ gate the planner enforces. None => skip the row."""
    fact = source_fact(getattr(draft, "caption", ""))
    if not fact:
        return None
    if caption_fn is not None:
        cap = caption_fn(fact)
    else:
        from . import gbp_planner
        cap = gbp_planner.generate_gbp_caption(fact, ctx["voice"], ctx["city"])
    if not cap:
        return None
    # belt: generate_gbp_caption already refuses a non-A+ caption, but an injected
    # caption_fn must not be able to route around the gate that keeps a degraded post
    # off a client's Google listing.
    if gbp.caption_issues(cap, city=ctx["city"]):
        return None
    return cap


# ---- the mirror ------------------------------------------------------------------------

def rows_for(base_key, drafts, *, library_path=None, store=None, ctx=None,
             caption_fn=None, image_fn=None, address_fn=None, logger=None):
    """The googlebusiness rows that mirror this build's FEED drafts. [] when the flag is
    off, the gym is not connected, its city/voice cannot be resolved, or nothing cleared
    the gates. NEVER raises: a mirror failure must never sink the gym's real month.

    Every row is built by gbp_planner._row, so its shape is the planner's own
    (account='googlebusiness', gbp_topic_type='STANDARD', gbp_cta_type/url, format
    'update'), it carries NO gbp_location_id (the worker binds the gym's connection at
    publish time), and its status is 'pending' — the owner's tap, never a coach screen.
    """
    log = logger or (lambda m: print(f"[gbp-mirror] {m}"))
    # PER-GYM ROLLOUT (same rung Echo Vision and the Story Studio render lane use): the
    # global flag arms every gym, or a gym is named in AGENT_GBP_MIRROR_GYMS. Checked per
    # gym rather than once, so one gym can prove the crop / caption / localize paths
    # against real production media before all 16 gyms' month builds run them.
    if not config.gbp_mirror_active_for(base_key):
        return []
    try:
        candidates = eligible_drafts(drafts)
        if not candidates:
            return []
        if not config.hosting_enabled():
            log(f"{base_key}: media hosting is not configured, so a 1200x900 crop cannot "
                "be hosted -> no Google rows (run where R2 hosting is set)")
            return []
        if ctx is None:
            ctx = resolve_context(base_key, store=store, address_fn=address_fn,
                                  logger=log)
        if not ctx:
            return []
        from . import gbp_planner
        rows = []
        skipped_caption = skipped_media = 0
        for draft in candidates:
            day_key = post_date_of(draft)
            img_url = (image_fn(draft, day_key) if image_fn is not None
                       else cropped_url(draft, ctx, library_path, log))
            if not img_url:
                skipped_media += 1
                continue
            cap = gbp_caption(draft, ctx, caption_fn=caption_fn)
            if not cap:
                skipped_caption += 1
                continue
            rows.append(gbp_planner._row(
                base_key, ctx["account_gen_key"], day_key, cap, img_url,
                topic_type="STANDARD",
                pillar=(getattr(draft, "category", "") or "").strip(),
                cta_type=gbp.DEFAULT_CTA, cta_url=ctx["cta_url"],
                fmt="update", status="pending"))
        log(f"{base_key}: mirrored {len(rows)} feed post(s) to Google Business "
            f"({skipped_caption} skipped on the A+ caption gate, {skipped_media} with no "
            f"croppable still, of {len(candidates)} feed candidate(s))")
        return rows
    except Exception as exc:  # noqa: BLE001 - the mirror never sinks the real month
        log(f"{base_key}: Google Business mirror skipped ({type(exc).__name__}: {exc})")
        return []
